# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.ror
canonical: https://interop.esante.gouv.fr/ig/fhir/ror
name: ROR
title: Répertoire national de l’Offre et des Ressources en santé et accompagnement médico-social
description: Ressources de conformité basées sur le modèle d'exposition 3.0 du ROR
publisher: 
  name: ANS
  url: https://esante.gouv.fr
dependencies:
  ans.annuaire.fhir.r4: 0.2.0
  hl7.fhir.fr.core: 1.1.0
  hl7.fhir.uv.bulkdata: 2.0.0
  ans.fr.securisation-transport: 1.2.0
status: active
version: 0.2.1
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
    shownav: 'true'



pages:
    index.md:
        title: Accueil
    specifications_fonctionnelles.md:
    specifications_techniques_1.md:
        title: Consultation des données capacitaires
    specifications_techniques_2.md:
        title: Consultation de l'offre (extraction)
    specifications_techniques_3.md:
        title: Recherche d'offre sur critères principaux
    specifications_techniques_4.md:
        title: Recherche d'offre avec données capacitaires
    specifications_techniques_8.md:
        title: Recherche d'offre sur la base d'informations tarifaires
    specifications_techniques_9.md:
        title: Recherche d'offre via une technique « Full text »  
    specifications_techniques_10.md:
        title: Création et Mise à jour du lieu de réalisation de l'offre  
    specifications_techniques_5.md:
        title: Signalement d'anomalie
    specifications_techniques_6.md:
        title: Mise à jour d'anomalie
    specifications_techniques_7.md:
        title: Consultation d'anomalie
    specifications_techniques_11.md:
        title: Consultation d'indicateurs de pilotage
    search_param.md:
        title: Critères de recherche
    modifiers.md:
        title: Paramètres et modificateurs de requêtes FHIR 
    mapping.md:
        title: Mapping FHIR du modèle de données du ROR
    downloads.md:
        title: Téléchargements et usages
        securite.md:
                title: Sécurité
    autres_ressources.md:
            title: Autres Ressources

menu:
    Accueil: index.html
    Spécifications fonctionnelles: specifications_fonctionnelles.html
    Spécifications techniques: 
        Consultation des données capacitaires: specifications_techniques_1.html
        Consultation de l'offre (extraction): specifications_techniques_2.html
        Recherche d'offre sur critères principaux: specifications_techniques_3.html
        Recherche d'offre avec données capacitaires: specifications_techniques_4.html
        Recherche d'offre sur la base d'informations tarifaires: specifications_techniques_8.html
        Recherche d'offre via une technique « Full text »: specifications_techniques_9.html  
        Création et Mise à jour du lieu de réalisation de l'offre: specifications_techniques_10.html
        Signalement d'anomalie: specifications_techniques_5.html
        Mise à jour d'anomalie: specifications_techniques_6.html
        Consultation d'anomalie: specifications_techniques_7.html
        Consultation d'indicateurs de pilotage: specifications_techniques_11.html        
        Critères de recherche: search_param.html
        Paramètres et modificateurs de requêtes FHIR: modifiers.html
    Mapping FHIR du modèle de données: mapping.html
    Ressources de conformité: artifacts.html
    Autres ressources:
        Sécurité: securite.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/
