# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.ror
canonical: https://interop.esante.gouv.fr/fhir/ig/ror
name: ROR
title: ROR
publisher: 
  name: ANS
  url: https://esante.gouv.fr
dependencies:
  ans.annuaire.fhir.r4: 0.2.0
  hl7.fhir.fr.core: 1.1.0
status: active
version: "3.0"
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build

parameters:
    shownav: 'true'


pages:
    index.md:
       title: Accueil
    specifications_fonctionnelles.md:
    specifications_techniques.md:
        specifications_techniques_1.md:
            title: Consultation des données capacitaires
        specifications_techniques_2.md:
            title: Consultation de l'offre (synchronisation)
        specifications_techniques_3.md:
            title: Recherche d'offre sur critères principaux
        specifications_techniques_4.md:
            title: Recherche d'offre avec données capacitaires
        search_param.md:
            title: Critères de recherche
        modifiers.md:
            title: Paramètres et modificateurs de requêtes FHIR
        annexes.md:
            title: Annexes    
    mapping.md:
    downloads.md:
        title: Téléchargements et usages
        securite.md:
                title: Sécurité
    autres_ressources.md:
            title: Autres Ressources
    about.md:
        title: A propos de ce guide

menu:
    Accueil: index.html
    Spécifications fonctionnelles: specifications_fonctionnelles.html
    Spécifications techniques: 
        Consultation des données capacitaires : specifications_techniques_1.html
        Consultation de l'offre (synchronisation) : specifications_techniques_2.html
        Recherche d'offre sur critères principaux : specifications_techniques_3.html
        Recherche d'offre avec données capacitaires : specifications_techniques_4.html
        Paramètres et modificateurs de requêtes FHIR : modifiers.html
        Critères de recherche : search_param.html
        Annexes : annexes.html
    Mapping FHIR du modèle de données: mapping.html
    Ressources de conformance: artifacts.html
    Téléchargements et usage: 
        Téléchargements: downloads.html
        Sécurité: securite.html
    Autres ressources:
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    A propos de ce guide: about.html