blank_issues_enabled: true
contact_links:
  - name: Projet ROR
    url: https://esante.gouv.fr/produits-services/repertoire-ror
    about: Pour plus d'informations sur le ROR vous pouvez accéder 
  - name: Support ROR
    email: ans-ror@esante.gouv.fr
    about: Pour toute demandes hors guide d'implémentation vous pouvez contacter le support du ROR à cette adresse
